Add description for calls to "should.exist"
Previously:

    AssertionError: expected undefined to exist

Now:

    AssertionError: missing element: <updated/>